apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-content
  template:
    metadata:
      labels:
        app: mongo-content
    spec:
      containers:
        - name: mongo-content
          image: mongo:6.0.4
          args: ["--dbpath", "/data/db"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-content-config
          volumeMounts:
            - mountPath: /data/db
              name: mongo-content-volume
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-content-init
      volumes:
        - name: mongo-content-volume
          persistentVolumeClaim:
            claimName: mongo-content-persistent-volume-claim
        - name: mongo-content-init
          configMap:
            name: mongo-content-init-config