server:
  port: 8080
  servlet:
    context-path: /v1/api/users


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop-auth
    username: workshop
    password: qwerty1234
  jpa:
    properties:
      hibernate:
        default_schema: main
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: none
      ddl-auto: update
  flyway:
#    enabled: true
    enabled: false
#    locations: classpath:db/migrations
    schemas: main
#    baseline-on-migrate: true
    baseline-version: 2
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 976193675212-b8009h7ptsgj2gqat9v0rsjdl8d2cum3.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
#  config:
#    activate:
#      on-profile: production


filesRoot: auth-service/src/main/resources/media/users/
publicRoles: >
  ROLE_CUSTOMER,
  ROLE_AUTHOR,
  ROLE_EXECUTOR
adminRoles: >
  ROLE_ADMIN, 
  ROLE_DEVELOPER, 
  ROLE_MODERATOR, 
  ROLE_SUPPORT


jwt:
  access-token:
    secret: ZGVzaWduX3dvcmtzaG9wX2FjY2Vzc19zZWNyZXQ=
    expired: 36000000
  refresh-token:
    expired: 86400000


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger.html


