apiVersion: v1
kind: PersistentVolume
metadata:
  name: application-auth-persistent-volume
  labels:
    type: local
    app: application-auth
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/application/auth"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-auth-persistent-volume-claim
  labels:
    app: application-auth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi