apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-persistent-volume
  labels:
    type: local
    app: rabbitmq
spec:
  storageClassName: rabbitmq-storage-class
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/rabbitmq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-persistent-volume-claim
  labels:
    app: rabbitmq
spec:
  storageClassName: rabbitmq-storage-class
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq-storage-class
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate