apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-metadata
  template:
    metadata:
      labels:
        app: mongo-metadata
    spec:
      containers:
        - name: mongo-metadata
          image: mongo:6.0.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-metadata-config
          volumeMounts:
            - mountPath: /data/db
              name: mongo-metadata-volume
      volumes:
        - name: mongo-metadata-volume
          persistentVolumeClaim:
            claimName: mongo-metadata-persistent-volume-claim