apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-metadata
  template:
    metadata:
      labels:
        app: mongo-metadata
    spec:
      containers:
        - name: mongo-metadata
          image: mongo:6.0.4
          args: ["--dbpath", "/data/db"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-metadata-config
          volumeMounts:
            - mountPath: /data/db
              name: mongo-metadata-volume
            - mountPath: /docker-entrypoint-initdb.d
              name: mongo-metadata-init
      volumes:
        - name: mongo-metadata-volume
          persistentVolumeClaim:
            claimName: mongo-metadata-persistent-volume-claim
        - name: mongo-content-init
          configMap:
            name: mongo-metadata-init-config