apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-metadata-persistent-volume
  labels:
    type: local
    app: mongo-metadata
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/metadata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-metadata-persistent-volume-claim
  labels:
    app: mongo-metadata
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi