apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-background
spec:
  selector:
    matchLabels:
      app: application-background
  template:
    metadata:
      labels:
        app: application-background
    spec:
      containers:
        - name: application-background
          image: daniilpanyushin/workshop-background:0.2
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: application-background-config
          volumeMounts:
            - mountPath: /src/main/resources
              name: application-background-volume
      volumes:
        - name: application-background-volume
          persistentVolumeClaim:
            claimName: application-background-persistent-volume-claim