server:
  servlet:
    context-path: /v1/api/content/


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop-auth
    username: workshop
    password: qwerty1234
  jpa:
    properties:
      hibernate:
        default_schema: main
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migrations
    schemas: main
    baseline-on-migrate: true
    baseline-version: 0.1
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


filesRoot: auth-service/src/main/resources/media/content/

jwt:
  access-token:
    secret: ZGVzaWduX3dvcmtzaG9wX2FjY2Vzc19zZWNyZXQ=
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger.html

