server:
  port: 8081
  servlet:
    context-path: /v1/api/content


spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: workshop-content
      username: workshop
      password: qwerty1234
      auto-index-creation: true
      authentication-database: workshop-content
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


filesRoot: content-service/src/main/resources/media/content/
maxFilesAmount: 15


jwt:
  access-token:
    secret: ZGVzaWduX3dvcmtzaG9wX2FjY2Vzc19zZWNyZXQ=


springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger.html

