apiVersion: v1
kind: Service
metadata:
  name: application-metadata-balancer
  labels:
    app: application-metadata
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: application-metadata